#!/usr/bin/env ruby

require('tempfile')

class String
def yellow; "\e[33m#{self}\e[0m" end
def gray;   "\e[37m#{self}\e[0m" end
end

puts "This is git-vim"

# default prefix
prefix = "%t: "

if (ARGV.size == 0)
  puts "I have nothing to do"
  exit
end
if (ARGV.size == 2)
  prefix = ARGV.shift.dup
else
  puts "# You haven't configured git-vim's prefix. Configure it like so:".yellow
  puts "#".yellow
  puts "#   git config core.editor '#{$0} \"ABCD-%t: \"'".yellow
  puts "#".yellow
end
filename = ARGV.shift()

branchname = `git rev-parse --abbrev-ref HEAD`
ticketNum = /\d\d\d+/.match(branchname)
ticketNum = if ticketNum==nil then nil else ticketNum[0] end

firstLine = File.open(filename).first

willPrepend = true
if (!firstLine.strip.empty?) 
  puts "This commit is already filled out with '#{firstLine.strip}'"
  willPrepend = false
  exec("vim #{filename}")
  # exit
end
if (ticketNum == nil)
  puts 'Could not find ticket number in branch name'
  willPrepend = false
  exec("vim #{filename} -c startinsert! ")
  # exit
end

if (willPrepend)
  puts 'I am prepending your ticket number for you'

  prefix.sub!(/%t/, ticketNum)

  prefixFile = Tempfile.new('prefix')
  prefixFile.write(prefix)
  prefixFile.close
  puts "Made temp file: #{prefixFile.path}"

  exec("vim #{filename} -c '0read #{prefixFile.path}' -c startinsert! ")

  prefixFile.unlink
  puts "Anything after exec() will not get executed"
end
