#!/usr/bin/env ruby

require('tempfile')

prefix = "UC-%t: "

puts "This is git-vim"

if (ARGV.size == 0)
  puts "I have nothing to do"
  exit
end
filename = ARGV.shift()

branchname = `git rev-parse --abbrev-ref HEAD`
ticketNum = /\d\d\d+/.match(branchname)
ticketNum = if ticketNum==nil then nil else ticketNum[0] end

firstLine = File.open(filename).first

willPrepend = true
if (!firstLine.strip.empty?) 
  puts "This commit is already filled out with '#{firstLine.strip}'"
  willPrepend = false
  exec("vim #{filename}")
  # exit
end
if (ticketNum == nil)
  puts 'Could not find ticket number in branch name'
  willPrepend = false
  exec("vim #{filename} -c startinsert! ")
  # exit
end

if (willPrepend)
  puts 'I am prepending your ticket number for you'

  prefix.sub!(/%t/, ticketNum)

  prefixFile = Tempfile.new('prefix')
  prefixFile.write(prefix)
  prefixFile.close
  puts "Made temp file: #{prefixFile.path}"

  exec("vim #{filename} -c '0read #{prefixFile.path}' -c startinsert! ")

  prefixFile.unlink
  puts "Anything after exec() will not get executed"
end
